exp_name: "pose_emb_script"
model_num: 1
optimizer_name: "sgd" # sgd ot adam
details: "model with  pose emned linear"
dataset_name: "cifar10"
seed: 64
num_epoch: 1
learning_rate: 1e-3
input_channel: 3
input_image_size: 224
patch_size: 16
# embedding_size: 768
num_head: 8
vit_depth: 12
batch_size: 8
num_class: 10
pos_emb_type: "linear" #linear sinsinusoidal rope
wandb_project: "vit-small-data"
output_dir: "results"